<?php

// ;$Id$

/**
* @file
* Modulo para exibir um bloco com
* informacoes do usuario.
*/

function custom_users_help($path, $arg){
  if ($path == 'admin/help#custom_users'){
    return t('Exibindo dados dos usuario de maneira customizada');
  }
}

/**
* Implements hook_block_info()
*/
function custom_users_block_info(){
  $block = array();
  $block['custom_users'] = array('info'=>t('Exibindo dados do usuario de maneira customizada.'),'cache'=>DRUPAL_NO_CACHE,);
  return $block;
}

/**
* Implements hook_block_view()
*/
function custom_users_block_view($block_name = ''){
  if($block_name == 'custom_users'){
    global $user;
    $account = user_load($user->uid);

    $block = array(
      'subject'=> t('Sobre o Autor'),
      'content' => user_view($account),
    );
    return $block;
  }
}